config:
  path: http://localhost

spring:
  application:
    name: authentication
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:configserver:${config.path}:8888
  cache:
    type: redis
    redis:
      time-to-live: 3600000 # TTL, ms (1h)
      cache-null-values: false
      key-prefix: true
  data:
    redis:
      host: ${redis.host:localhost}
      port: ${redis.port:6379}

server:
  port: 8092
  servlet:
    context-path: /api
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
    relaxed-query-chars: '|,{,},[,]'
management:
  tracing:
    sampling:
      probability: 1.0

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
    path: /v1/auth/v3/api-docs
