language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "febfes"
    token:
      secure: "$SONAR_TOKEN"
jdk:
  - oraclejdk17
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'