spring:
  application:
    name: gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 20000
        response-timeout: 7s
      discovery:
        locator:
          enabled: true
      routes:
        - id: notifications
          uri: http://localhost:8091
          predicates:
            - Path=/api/v1/notifications/**
        - id: monolith
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/**
  config:
    import: optional:configserver:http://localhost:8200

server:
  port: 8061
management:
  tracing:
    sampling:
      probability: 1.0

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    urls:
      - name: monolith
        url: /api/v1/v3/api-docs
      - name: notification-service
        url: /api/v1/notifications/v3/api-docs
    enabled: true
    config-url: /v3/api-docs/swagger-config
    tagsSorter: alpha
