## Build stage
FROM amazoncorretto:17-alpine AS build
WORKDIR /home/api-gateway

COPY ./gateway/.mvn/ .mvn/
COPY ./gateway/mvnw ./mvnw
COPY ./gateway/pom.xml ./pom.xml
COPY ./gateway/src ./src/

# build commons module first
COPY ./febfes-commons ./febfes-commons

RUN chmod +x mvnw
RUN sed -i 's/\r$//' mvnw
RUN ./mvnw -f febfes-commons/pom.xml clean install -DskipTests

# run with the SH path
RUN /bin/sh mvnw dependency:resolve
RUN ./mvnw clean install -Dmaven.test.skip

## Package stage
FROM amazoncorretto:17-alpine
WORKDIR /home/api-gateway

COPY --from=build /home/api-gateway/target/*.jar /home/api-gateway/*.jar
EXPOSE 8061
ENTRYPOINT ["java", "-jar", "/home/api-gateway/*.jar"]
