## Build stage
FROM amazoncorretto:17-alpine AS build
WORKDIR /home/authentication

COPY ./authentication/.mvn/ .mvn/
COPY ./authentication/mvnw ./authentication/pom.xml ./authentication/lombok.config ./
COPY ./authentication/src ./src/
#COPY ./scripts/wait-for-it.sh /home/authentication/wait-for-it.sh

#RUN chmod +x wait-for-it.sh
RUN chmod +x mvnw
# clean up the file
RUN sed -i 's/\r$//' mvnw
RUN ./mvnw clean install -Dmaven.test.skip

## Package stage
FROM amazoncorretto:17-alpine
WORKDIR /home/authentication

COPY --from=build /home/authentication/target/*.jar /home/authentication/*.jar
EXPOSE 8092
ENTRYPOINT ["java", "-jar", "/home/authentication/*.jar"]
#ENTRYPOINT ["/home/authentication/wait-for-it.sh", "host.docker.internal:8888", "--", "java", "-jar", "/home/authentication/*.jar"]
