## Build stage
FROM openjdk:17-alpine AS build
WORKDIR /home/api-gateway
COPY ../gateway/.mvn/ .mvn/
COPY ../gateway/mvnw ../gateway/pom.xml ../gateway/lombok.config ./

COPY ../gateway/src ./src/
RUN ../gateway/mvnw clean install -Dmaven.test.skip

## Package stage
FROM eclipse-temurin:17-jre-alpine
WORKDIR /home/api-gateway

COPY --from=build /home/api-gateway/target/*.jar /home/api-gateway/*.jar
EXPOSE 8061
ENTRYPOINT ["java", "-jar", "/home/api-gateway/*.jar"]
