## Build stage
FROM amazoncorretto:17-alpine AS build
WORKDIR /home/authentication

COPY ./authentication/.mvn/ .mvn/
COPY ./authentication/mvnw ./mvnw
COPY ./authentication/pom.xml ./pom.xml
COPY ./authentication/lombok.config ./lombok.config
COPY ./authentication/src ./src/

# build commons module first
COPY ./febfes-commons ./febfes-commons

RUN chmod +x mvnw
RUN sed -i 's/\r$//' mvnw
RUN ./mvnw -f febfes-commons/pom.xml clean install -DskipTests

RUN ./mvnw clean install -Dmaven.test.skip

## Package stage
FROM amazoncorretto:17-alpine
WORKDIR /home/authentication

COPY --from=build /home/authentication/target/*.jar /home/authentication/*.jar
EXPOSE 8092
ENTRYPOINT ["java", "-jar", "/home/authentication/*.jar"]
