## Build stage
FROM amazoncorretto:17-alpine AS build
WORKDIR /home/notification

COPY ./notification/.mvn/ .mvn/
COPY ./notification/mvnw ./mvnw
COPY ./notification/pom.xml ./pom.xml
COPY ./notification/lombok.config ./lombok.config
COPY ./notification/src ./src/

# build commons module first
COPY ./febfes-commons ./febfes-commons

RUN chmod +x mvnw
RUN sed -i 's/\r$//' mvnw
RUN ./mvnw -f febfes-commons/pom.xml clean install -DskipTests

RUN ./mvnw clean install -Dmaven.test.skip

## Package stage
FROM amazoncorretto:17-alpine
WORKDIR /home/notification

COPY --from=build /home/notification/target/*.jar /home/notification/*.jar
EXPOSE 8091
ENTRYPOINT ["java", "-jar", "/home/notification/*.jar"]
