## Build stage
FROM openjdk:17-alpine AS build
WORKDIR /home/notification
COPY ../notification/.mvn/ .mvn/
COPY ../notification/mvnw ../notification/pom.xml ../notification/lombok.config ./

COPY ../notification/src ./src/
RUN ../notification/mvnw clean install -Dmaven.test.skip

## Package stage
FROM eclipse-temurin:17-jre-alpine
WORKDIR /home/notification

COPY --from=build /home/notification/target/*.jar /home/notification/*.jar
EXPOSE 8061
ENTRYPOINT ["java", "-jar", "/home/notification/*.jar"]
