version: '3.9'

services:
  postgres:
    image: postgres:13.3
    container_name: postgres-ff-tm
    restart: always
    env_file:
      .env
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  api:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8090:8090"
    env_file:
      .env
#    environment:
#      datasource.url: "jdbc:postgresql://localhost:5432/${POSTGRES_DB}"
#      datasource.user: ${POSTGRES_USER}
#      datasource.password: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres
