global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'redis'
    static_configs:
      - targets: [ 'redis-exporter:9121' ]
  - job_name: 'hazelcast'
    metrics_path: /prometheus
    static_configs:
      - targets: [ 'hazelcast-mc:8180' ]
