create table public.user_entity
(
    id                 bigint generated by default as identity primary key,
    create_date        timestamp   default now(),
    email              varchar(50)                              not null unique,
    username           varchar(50)                              not null unique,
    encrypted_password varchar(100)                             not null,
    first_name         varchar(50),
    last_name          varchar(50),
    display_name       varchar(50) default 'defaultDisplayName' not null
);

create table refresh_token
(
    id          bigint generated by default as identity primary key,
    create_date timestamp    not null,
    token       varchar(512) not null unique,
    expiry_date timestamp    not null,
    user_id     bigint,
    constraint fk_refresh_token_user foreign key (user_id) references user_entity (id)
);

INSERT INTO public.user_entity (id,
                                create_date,
                                email,
                                username,
                                encrypted_password,
                                first_name,
                                last_name,
                                display_name)
VALUES (1,
        NOW(),
        'testuser1@example.com',
        'testuser1',
        '$2a$10$abcdefghijklmnopqrstuv', -- пример зашифрованного пароля
        'Test',
        'User',
        'TestUserDisplay');
