spring:
  application:
    name: authentication
  boot:
    admin:
      client:
        url: ${config.path}:8095
server:
  port: 8092
management:
  endpoints:
    web:
      exposure:
        include: '*'
# Base URL to ff-tm-back service used by Feign clients
ff-tm-back:
  url: ${config.path}:8090/api

grpc:
  client:
    role-service:
      address: ${role.service.address:static://${config.path}:9091}
      negotiationType: PLAINTEXT
