spring:
  application:
    name: authentication
  boot:
    admin:
      client:
        url: ${config.path}:8095
server:
  port: 8092
management:
  endpoints:
    web:
      exposure:
        include: '*'
