spring:
  application:
    name: ff-tm-back-monolith
  boot:
    admin:
      client:
        url: ${config.path}:8095
  cloud:
    openfeign:
      okhttp:
        enabled: true
      httpclient:
        enabled: false
  autoconfigure:
    exclude:
      - net.devh.boot.grpc.client.autoconfigure.GrpcServerMetricAutoConfiguration
server:
  port: 8090
folders:
  user-pic: /home/febfes/userPics/
  task-files: /home/febfes/files/
management:
  endpoints:
    web:
      exposure:
        include: '*'
grpc:
  server:
    metrics:
      enabled: false
    port: 9091
