spring:
  gateway:
    excluded-urls: /v1/notifications/swagger-ui,/v1/notifications/v3/api-docs,/v1/swagger-ui,/v1/v3/api-docs
    validate-token-url: ${config.path}:8092/api/v1/auth/validate-token
  application:
    name: gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 20000
        response-timeout: 7s
      discovery:
        locator:
          enabled: true
      routes:
        - id: notifications
          uri: ${config.path}:8091
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - TokenValidationFilter

        - id: authentication
          uri: ${config.path}:8092
          predicates:
            - Path=/api/v1/auth/**

        - id: users
          uri: ${config.path}:8092
          predicates:
            - Path=/api/v1/users/**
          filters:
            - TokenValidationFilter

        - id: monolith
          uri: ${config.path}:8090
          predicates:
            - Path=/api/v1/**
          filters:
            - TokenValidationFilter

server:
  port: 8061
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: '*'

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    urls:
      - name: monolith
        url: /api/v1/v3/api-docs
      - name: notification-service
        url: /api/v1/notifications/v3/api-docs
      - name: authentication-service
        url: /api/v1/auth/v3/api-docs
    enabled: true
    config-url: /v3/api-docs/swagger-config

  boot:
    admin:
      client:
        url: ${config.path}:8095
