server:
  port: 8888

config:
  host: localhost
  path: http://localhost

spring:
  boot:
    admin:
      client:
        url: ${config.path}:8095
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        bootstrap: false
        native:
          search-locations: classpath:/configurations/

management:
  endpoints:
    web:
      exposure:
        include: '*'
