server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}

springdoc:
  swagger-ui:
    tagsSorter: alpha

jwt:
  secret: ${jwt.secret}
  # Access token is valid 6 hours
  expirationDateDuration: 6H
  # Refresh token is valid 24 hours
  refreshExpirationDateDuration: 24H

gateway:
#  TODO: headers: uri-header maybe?
  uri-header: X-init-uri
  role-header: X-user-role
