server:
  port: 8888

config:
  host: localhost
  path: http://${config.host}

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        bootstrap: false
        native:
          search-locations: classpath:/configurations/
