name: SonarCloud - FF-TM-BACK
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ff-tm-back:
    name: Build and analyze FF-TM-BACK
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.head.ref, 'ff-tm-back') || contains(github.event.pull_request.base.ref, 'ff-tm-back')
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('ff-tm-back/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze FF-TM-BACK
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd ff-tm-back
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=FEBFES_FF-TM-BACK
