name: SonarCloud - Notification
on:
  push:
    branches:
      - main
    paths:
      - 'notification/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'notification/**'

jobs:
  notification:
    name: Build and analyze Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('notification/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze Notification
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd notification
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=FEBFES_FF-TM-BACK
