#name: SonarCloud
#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    types: [ opened, synchronize, reopened ]
#
#jobs:
#  authentication:
#    name: Build and analyze Authentication
#    runs-on: ubuntu-latest
#    if: contains(github.event.pull_request.head.ref, 'authentication') || contains(github.event.pull_request.base.ref, 'authentication')
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: maven
#      - name: Cache Maven packages
#        uses: actions/cache@v3
#        with:
#          path: ~/.m2
#          key: ${{ runner.os }}-m2-${{ hashFiles('authentication/pom.xml') }}
#          restore-keys: ${{ runner.os }}-m2
#      - name: Build and analyze Authentication
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#        run: |
#          cd authentication
#          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=FEBFES_FF-TM-BACK
#
#  ff-tm-back:
#    name: Build and analyze FF-TM-BACK monolith
#    runs-on: ubuntu-latest
#    if: contains(github.event.pull_request.head.ref, 'ff-tm-back') || contains(github.event.pull_request.base.ref, 'ff-tm-back')
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: maven
#      - name: Cache Maven packages
#        uses: actions/cache@v3
#        with:
#          path: ~/.m2
#          key: ${{ runner.os }}-m2-${{ hashFiles('ff-tm-back/pom.xml') }}
#          restore-keys: ${{ runner.os }}-m2
#      - name: Build and analyze FF-TM-BACK
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#        run: |
#          cd ff-tm-back
#          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=FEBFES_FF-TM-BACK
#  gateway:
#    name: Build and analyze Gateway
#    runs-on: ubuntu-latest
#    if: contains(github.event.pull_request.head.ref, 'gateway') || contains(github.event.pull_request.base.ref, 'gateway')
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: maven
#      - name: Cache Maven packages
#        uses: actions/cache@v3
#        with:
#          path: ~/.m2
#          key: ${{ runner.os }}-m2-${{ hashFiles('gateway/pom.xml') }}
#          restore-keys: ${{ runner.os }}-m2
#      - name: Build and analyze Gateway
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#        run: |
#          cd gateway
#          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=FEBFES_FF-TM-BACK
#
#  config-server:
#    name: Build and analyze Config server
#    runs-on: ubuntu-latest
#    if: contains(github.event.pull_request.head.ref, 'config-server') || contains(github.event.pull_request.base.ref, 'config-server')
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: maven
#      - name: Cache Maven packages
#        uses: actions/cache@v3
#        with:
#          path: ~/.m2
#          key: ${{ runner.os }}-m2-${{ hashFiles('config-server/pom.xml') }}
#          restore-keys: ${{ runner.os }}-m2
#      - name: Build and analyze Config-server
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#        run: |
#          cd config-server
#          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=FEBFES_FF-TM-BACK
#  notification:
#    name: Build and analyze Notification
#    runs-on: ubuntu-latest
#    if: contains(github.event.pull_request.head.ref, 'notification') || contains(github.event.pull_request.base.ref, 'notification')
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: maven
#      - name: Cache Maven packages
#        uses: actions/cache@v3
#        with:
#          path: ~/.m2
#          key: ${{ runner.os }}-m2-${{ hashFiles('notification/pom.xml') }}
#          restore-keys: ${{ runner.os }}-m2
#      - name: Build and analyze Notification
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#        run: |
#          cd notification
#          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=FEBFES_FF-TM-BACK
